# Generated by Django 4.0.4 on 2022-04-16 17:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('domicilio', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Empleado_Docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoConCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Cargo_EmpleadoConCargo', to='asistencia.cargo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Usuario_EmpleadoConCargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=45)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('dia_semana', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VacacionesEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Empleado_VacacionesEmpleado', to='asistencia.empleadoconcargo')),
            ],
        ),
        migrations.CreateModel(
            name='VacacionesDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Docente_VacacionesDocente', to='asistencia.docente')),
            ],
        ),
        migrations.CreateModel(
            name='PermisosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('motivo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Empleado_PermisosEmpleado', to='asistencia.empleadoconcargo')),
            ],
        ),
        migrations.CreateModel(
            name='PermisosDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('motivo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
                ('idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Docente_PermisosDocente', to='asistencia.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=45)),
                ('estado', models.CharField(max_length=1)),
                ('idJornadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_jornada_Horario', to='asistencia.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=6)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('dia_semana', models.CharField(max_length=10)),
                ('salon', models.CharField(max_length=4)),
                ('sede', models.CharField(max_length=10)),
                ('cupos', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Docente_Curso', to='asistencia.docente')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Materia_Curso', to='asistencia.materia')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='idDependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Dependencia_Cargo', to='asistencia.dependencia'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='idHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Horario_Cargo', to='asistencia.horario'),
        ),
        migrations.CreateModel(
            name='AsitenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField()),
                ('observacion', models.CharField(max_length=45)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Empleado_AsistenciaEmpleado', to='asistencia.empleadoconcargo')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField()),
                ('tema', models.CharField(max_length=20)),
                ('dificultades', models.CharField(max_length=45)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Curso_AsistenciaDocente', to='asistencia.curso')),
            ],
        ),
    ]
