# Generated by Django 3.2.12 on 2022-05-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20220516_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dependencia', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VacacionesEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vacacion_empleado', to='asistencia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(max_length=1)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_permiso_empleado', to='asistencia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Horario_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1)),
                ('cedula_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_horario_empleado_cedula', to='asistencia.empleado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_horario_empleado', to='asistencia.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Cargo_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalle_cargo', to='asistencia.cargo')),
                ('cedula_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalle_empleado_cargo', to='asistencia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('salon', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=1)),
                ('cedula_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_docente', to='asistencia.empleado')),
                ('codigo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_materia', to='asistencia.materia')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_dependencia', to='asistencia.dependencia'),
        ),
        migrations.CreateModel(
            name='Asistencia_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_asitencia', models.DateTimeField()),
                ('observacion', models.CharField(max_length=45)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_asistencia_cedula', to='asistencia.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_asitencia', models.DateTimeField()),
                ('observacion', models.CharField(max_length=45)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_asistencia_cedula_docente', to='asistencia.empleado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_asistencia_docente_curso', to='asistencia.curso')),
            ],
        ),
    ]
